### ISSUE TITLE
UI + polishing

### ISSUE THREAD

**Issue by dasBottles** [dasBottles/project1#31]
## To-Do
- [ ] Create function to dynamically make columns
- [ ] Make historyModal content call API
- [ ] Load last recipe called on user login

## Acceptance Criteria
- [ ] Ingredients are 6/column, any more creates new col6
- [ ] historyModal titles clickable, clicking reads item id and runs search
- [ ] recipeCard is visible on login, showing last recipe called
